import type { ReasonCode } from "./derive.js";

export type Language = "zh" | "en";

/**
 * The plugin SDK has no locale API, so the browser's language decides unless
 * the plugin setting pins one. Every user-facing string lives here.
 */
export function resolveLanguage(setting: "auto" | Language | undefined): Language {
  if (setting === "zh" || setting === "en") return setting;
  const tag = typeof navigator === "undefined" ? "" : navigator.language;
  return tag.toLowerCase().startsWith("zh") ? "zh" : "en";
}

const zh = {
  pmo: "PMO",
  pmoHint: { running: "巡检中", pendingInteraction: "在问你", error: "出错了", idle: "问它任何 task 的事" },
  now: "现在",
  nowReason: { unread: "新结果", seen: "刚看过", current: "当前" },
  scratch: "临时",
  scratchEmpty: "最近 7 天没有独立线程",
  showAll: (n: number) => `全部 ${n} 条`,
  showLess: "收起",
  more: "更多",
  waiting: "等 CI / 等别人",
  stalled: "停了",
  backlog: "未开始",
  done: "最近完成",
  promote: "提升为 task",
  promoting: "…",
  archived: "已归档",
  state: { running: "在跑", asking: "在问你", error: "出错", unread: "有新消息" },
  noThread: "还没有线程",
  loading: "加载中…",
  loadError: "加载 task 失败。",
  promoteError: "提升失败",
  reason: {
    ended: "已结束",
    notStarted: "未开始",
    noThreads: "没有线程，写 next 或关掉",
    asking: "在问你",
    error: "线程出错",
    running: "在跑",
    ciPending: "CI 运行中",
    ciFailed: "CI 失败",
    reviewPassing: "等你 review",
    review: "等你 review",
    stalled: "没有 next",
    waitingAgent: "等 agent",
  } satisfies Record<ReasonCode, string>,
  board: {
    title: "全景",
    all: "全部",
    doneThisWeek: (n: number) => `本周完成 ${n} 件`,
    cycle: (days: number) => `近 30 天中位周期 ${days} 天`,
    columns: {
      you: ["等你", "agent 在问、PR 等 review"],
      running: ["在跑", "agent 正在工作"],
      waiting: ["等 CI / 等别人", "有 next，不用你动"],
      stalled: ["停了", "没有 next，写一条或关掉"],
      backlog: ["未开始", "还没有线程"],
      done: ["最近完成", "30 天内结束"],
    },
    none: "没有",
    threads: (n: number) => `${n} 线程`,
    took: (days: number) => `用时 ${days}d`,
    archiveStale: "归档 30 天没动的",
    willArchive: (n: number) => `将归档 ${n} 件：`,
    cancel: "取消",
    confirmArchive: "确认归档",
    archiving: "归档中…",
    archiveError: "归档失败",
    archivedPartial: (done: number, total: number) => `只归档了 ${done} / ${total} 件，其余已重新活跃或更新失败`,
  },
  inbox: {
    kicker: "收件箱",
    title: "现在轮到我的",
    empty: "没有事轮到你",
    openThreadAnswer: "打开线程回答",
    openPr: (n: number) => `打开 PR #${n}`,
    openThread: "打开线程",
    noThread: "暂无线程",
    writeNext: "写下一步",
    nextPlaceholder: "下一步谁做什么",
    save: "保存",
    saving: "保存中…",
    saveError: "保存失败",
    more: (n: number) => `还有 ${n} 件`,
    refresh: "刷新收件箱",
  },
  panel: {
    title: "所属 task",
    ended: "这个 task 已结束。",
    unfiled: "这个线程还没有归档到 task。",
    promote: "提升为 task",
    busy: "处理中…",
    fileTo: "归到已有 task",
    rebindTo: "改绑到 task key",
    file: "归档",
    rebind: "改绑",
    rebindError: "改绑失败",
    promoteError: "提升失败",
    lastHere: "你上次在这里做到",
    next: "Next",
    noNext: "未写 next",
    currentThread: "当前线程",
    siblings: "兄弟线程",
    pr: "PR",
    keyPlaceholder: "例如 AK-12",
  },
  newTask: {
    title: "先建 task",
    lead: "输入一句标题，创建 task 并启动首个线程。",
    personalFallback: "未选项目时建到 Personal。",
    linkedProject: "建到当前项目关联的 tracker project。",
    preset: "首个线程用插件设置里的 delegation preset 启动（默认 Luna）。",
    placeholder: "我要做什么？",
    create: "创建并开始",
    creating: "创建中…",
    error: "创建失败。",
  },
};

const en: typeof zh = {
  pmo: "PMO",
  pmoHint: {
    running: "sweeping",
    pendingInteraction: "asking you",
    error: "errored",
    idle: "ask it anything about tasks",
  },
  now: "Now",
  nowReason: { unread: "new result", seen: "just viewed", current: "current" },
  scratch: "Scratch",
  scratchEmpty: "No standalone threads in the last 7 days",
  showAll: (n) => `All ${n}`,
  showLess: "Less",
  more: "More",
  waiting: "Waiting on CI / others",
  stalled: "Stalled",
  backlog: "Not started",
  done: "Recently done",
  promote: "Make a task",
  promoting: "…",
  archived: "archived",
  state: { running: "running", asking: "asking you", error: "errored", unread: "unread" },
  noThread: "No thread yet",
  loading: "Loading…",
  loadError: "Could not load tasks.",
  promoteError: "Could not promote thread.",
  reason: {
    ended: "ended",
    notStarted: "not started",
    noThreads: "no threads; write a next or close it",
    asking: "asking you",
    error: "thread errored",
    running: "running",
    ciPending: "CI running",
    ciFailed: "CI failed",
    reviewPassing: "your review",
    review: "your review",
    stalled: "no next",
    waitingAgent: "waiting on agent",
  },
  board: {
    title: "Board",
    all: "All",
    doneThisWeek: (n) => `${n} done this week`,
    cycle: (days) => `median cycle ${days}d over 30 days`,
    columns: {
      you: ["You", "agent asking, PR awaiting review"],
      running: ["Running", "agent at work"],
      waiting: ["Waiting", "has a next; nothing for you"],
      stalled: ["Stalled", "no next; write one or close it"],
      backlog: ["Not started", "no thread yet"],
      done: ["Recently done", "finished within 30 days"],
    },
    none: "None",
    threads: (n) => `${n} thread${n === 1 ? "" : "s"}`,
    took: (days) => `took ${days}d`,
    archiveStale: "Archive 30-day idle",
    willArchive: (n) => `Archive ${n} task${n === 1 ? "" : "s"}:`,
    cancel: "Cancel",
    confirmArchive: "Archive",
    archiving: "Archiving…",
    archiveError: "Could not archive",
    archivedPartial: (done, total) => `Archived ${done} / ${total}; the rest became active again or failed`,
  },
  inbox: {
    kicker: "Inbox",
    title: "On me now",
    empty: "Nothing needs you",
    openThreadAnswer: "Open thread and answer",
    openPr: (n) => `Open PR #${n}`,
    openThread: "Open thread",
    noThread: "No thread",
    writeNext: "Write the next step",
    nextPlaceholder: "Who does what next",
    save: "Save",
    saving: "Saving…",
    saveError: "Could not save",
    more: (n) => `${n} more`,
    refresh: "Refresh inbox",
  },
  panel: {
    title: "Task",
    ended: "This task has ended.",
    unfiled: "This thread is not filed under a task.",
    promote: "Make a task",
    busy: "Working…",
    fileTo: "File under an existing task",
    rebindTo: "Move to task key",
    file: "File",
    rebind: "Move",
    rebindError: "Could not move thread",
    promoteError: "Could not promote thread",
    lastHere: "Where you left off",
    next: "Next",
    noNext: "No next written",
    currentThread: "This thread",
    siblings: "Sibling threads",
    pr: "PR",
    keyPlaceholder: "e.g. AK-12",
  },
  newTask: {
    title: "Task first",
    lead: "One line of title creates the task and starts its first thread.",
    personalFallback: "Without a project it goes to Personal.",
    linkedProject: "Goes to the tracker project linked to this project.",
    preset: "The first thread uses the plugin's delegation preset (default Luna).",
    placeholder: "What am I doing?",
    create: "Create and start",
    creating: "Creating…",
    error: "Could not create task.",
  },
};

export type Strings = typeof zh;
export const STRINGS: Record<Language, Strings> = { zh, en };

export function reasonText(t: Strings, reason: ReasonCode, pr: number | null): string {
  const base = t.reason[reason];
  return pr === null ? base : `PR #${pr} · ${base}`;
}
